/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_code_jdde_ddeml_DdeAPI */

#ifndef _Included_com_google_code_jdde_ddeml_DdeAPI
#define _Included_com_google_code_jdde_ddeml_DdeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    AbandonTransaction
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_AbandonTransaction
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    ClientTransaction
 * Signature: (I[BILjava/lang/String;IIILcom/google/code/jdde/ddeml/Pointer;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_ClientTransaction
  (JNIEnv *, jclass, jint, jbyteArray, jint, jstring, jint, jint, jint, jobject);

/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    Connect
 * Signature: (ILjava/lang/String;Ljava/lang/String;Lcom/google/code/jdde/ddeml/ConvContext;)I
 */
JNIEXPORT jint JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_Connect
  (JNIEnv *, jclass, jint, jstring, jstring, jobject);

/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    Disconnect
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_Disconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    GetLastError
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_GetLastError
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    Initialize
 * Signature: (Lcom/google/code/jdde/ddeml/Pointer;I)I
 */
JNIEXPORT jint JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_Initialize
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    NameService
 * Signature: (ILjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_NameService
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    PostAdvise
 * Signature: (ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_PostAdvise
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_google_code_jdde_ddeml_DdeAPI
 * Method:    Uninitialize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_code_jdde_ddeml_DdeAPI_Uninitialize
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
