/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_code_jdde_ddeml_WinAPI */

#ifndef _Included_com_google_code_jdde_ddeml_WinAPI
#define _Included_com_google_code_jdde_ddeml_WinAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_code_jdde_ddeml_WinAPI
 * Method:    GetCurrentThreadId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_code_jdde_ddeml_WinAPI_GetCurrentThreadId
  (JNIEnv *, jclass);

/*
 * Class:     com_google_code_jdde_ddeml_WinAPI
 * Method:    GetLastError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_google_code_jdde_ddeml_WinAPI_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     com_google_code_jdde_ddeml_WinAPI
 * Method:    KillTimer
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_code_jdde_ddeml_WinAPI_KillTimer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_google_code_jdde_ddeml_WinAPI
 * Method:    PostThreadMessage
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_code_jdde_ddeml_WinAPI_PostThreadMessage
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_google_code_jdde_ddeml_WinAPI
 * Method:    RegisterClipboardFormat
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_google_code_jdde_ddeml_WinAPI_RegisterClipboardFormat
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_google_code_jdde_ddeml_WinAPI
 * Method:    RegisterWindowMessage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_google_code_jdde_ddeml_WinAPI_RegisterWindowMessage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_google_code_jdde_ddeml_WinAPI
 * Method:    SetTimer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_google_code_jdde_ddeml_WinAPI_SetTimer
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_google_code_jdde_ddeml_WinAPI
 * Method:    WaitOnMessageLoop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_code_jdde_ddeml_WinAPI_WaitOnMessageLoop
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
